### ISSUE TITLE
manager.getSamples() does not exist

### ISSUE THREAD

**Issue by thely** [petervdn/sample-manager#4]
Found this through checking the object prototype in the logs. `loadAllSamples()`, `loadSamples()`, and `loadSampleByName()` all exist, but only `getAllSamples()` and `getSampleByName()` are available (no `getSamples()`) to the manager.

I'm guessing this is an error with the readme? The last section ("retrieving samples") mentions `getSamples()`, but should probably be `getAllSamples()` instead.

**Comment by petervdn** [comment]
hey, thanks for pointing this out. i will look into it!

**Comment by petervdn** [comment]
i updated the readme (it says `getAllSamples` now)
